DROP DATABASE IF EXISTS	Testing_System_Assignment_1;
CREATE DATABASE Testing_System_Assignment_1;
USE	Testing_System_Assignment_1;
CREATE TABLE	Department (
DepartmentID	TINYINT UNSIGNED,
DepartmentName	VARCHAR(20)
);
CREATE TABLE	Position (
PositionID	TINYINT UNSIGNED,
PositionName	VARCHAR(20)
);
CREATE TABLE	Account_	(
AccountID	TINYINT UNSIGNED,
Email	VARCHAR(30),
Username	CHAR(15),
Fullname	VARCHAR(30),
DepartmentID	VARCHAR(20),
PositionID	VARCHAR(30),
CreateDate	DATETIME 
);
CREATE TABLE	Group_	(
GroupID	TINYINT UNSIGNED,
GroupName	VARCHAR(30),
CreatorID	TINYINT UNSIGNED,
CreateDate	DATETIME
);
CREATE TABLE	GroupAccount	(
GroupID	TINYINT UNSIGNED,
AccountID	TINYINT UNSIGNED,
JoinDate DATETIME
);
CREATE TABLE	TypeQuestion (
TypeID TINYINT UNSIGNED,
TypeName VARCHAR(50)
);
CREATE TABLE	CategoryQuestion (
CategoryID TINYINT UNSIGNED,
CategoryName CHAR(20)
);
CREATE TABLE	Question (
QuestionID	TINYINT UNSIGNED,
Content	VARCHAR(100),
CategoryID	TINYINT UNSIGNED,
TypeID	TINYINT UNSIGNED,
CreatorID	TINYINT UNSIGNED,
CreateDate	DATETIME
);
CREATE TABLE	Answer (
AnswerID	TINYINT UNSIGNED,
Content	VARCHAR(300),
QuestionID	TINYINT UNSIGNED,
isCorrect	ENUM('Đúng''Sai')
);
CREATE TABLE	EXAM (
ExamID	TINYINT UNSIGNED,
Code_ CHAR(10),
Title	VARCHAR(30),
CategoryID	TINYINT UNSIGNED,
Duration CHAR(10),
CreatorID TINYINT UNSIGNED,
CreateDate	DATETIME
);
CREATE TABLE	ExamQuestions (
ExamID	TINYINT UNSIGNED,
QuestionID	TINYINT UNSIGNED 
);